---
title: "Assignment 3: Airbnb NY Data Analysis"
output: html_document
date: "2025-11-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE}
install.packages("pacman")

library(pacman)

pacman::p_load(tidyverse, 
               lme4,
               lmerTest,
               MuMIn,
               sjPlot)

```

```{r}
data <- read_csv("/work/CulturalDataScience/NY_data_with_sent.csv",show_col_types = FALSE)
```

```{r}
# Rune
# Setting room type to factor to allow for leveled analysis
data$room_type <- as.factor(data$room_type)
# Inspecting data types to see if anything should be coerced
spec(data)
```


```{r}
# Markus
# Omitting zero pricing (uninformative and creates NAs when log transformed)
data <- data %>% filter(price>0)
```

```{r}
# Rune
# Omitting NAs in the name column (creates NAs when passed to VADER)
data <- data[!is.na(data$name), ]
# Log transforming price variable and saving to new column
data$log_price <- log(data$price)
```

```{r}
# Markus
# Selecting relevant columns
data <- data %>% select(price, name,vs_compound,log_price, neighbourhood, room_type)
```

```{r}
# Rune
# Creating a mixed effects model that allows for a random intercept for neighbourhood and room type (whole aparment or only room) as these intuitively carry price information
model_sent_neighbor <- lmerTest::lmer(log_price ~ vs_compound + (1|neighbourhood) + (1|room_type), data=data)

model_sent_neighbor_no_log <- lmerTest::lmer(price ~ vs_compound + (1|neighbourhood) + (1|room_type), data=data)

# From the summary we see a statistically significant negative effect of sentiment on the price per night
summary(model_sent_neighbor)

# We see an adjusted r-squared value of .000542
r.squaredGLMM(model_sent_neighbor)
```

```{r}
# Markus
# Log transformation of price variable has moved the residuals closer to the theoretical line for normality of residuals, but still does not meet the assumptions - we will touch on this in limitations.
qqnorm(residuals(model_sent_neighbor))
```

```{r}
# Rune
plot(model_sent_neighbor)
```


```{r}
# Markus
# Plotting the model for a visual representation of the observed effect.
plot_model(model_sent_neighbor, type="pred", terms="vs_compound",
           axis.title = c("Vader Sentiment Compound Score", "Logarithm of price per night in USD"),
           title = "Predicted Logarithmic Price by Compound Score",
           ci.lvl=NA) +
  theme_minimal()
```
